name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */4 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Plugins & Options
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 20
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_skipped: EthernautCTF
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_playlist: >-
            https://music.youtube.com/playlist?list=PLmjXnqwE5MTT_TMHx0LYvkYJsEypAdA--
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, JSON
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_ignored: scss, css, html


